### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED Error

### ISSUE THREAD

**Issue by razer-santhosh** [tolotrasamuel/account_picker#11]
java.lang.SecurityException: com.example.app:One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts.

E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#fman.smart_auth( 5268): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
E/MethodChannel#fman.smart_auth( 5268): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
E/MethodChannel#fman.smart_auth( 5268): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
E/MethodChannel#fman.smart_auth( 5268): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
E/MethodChannel#fman.smart_auth( 5268): 	at fman.ge.smart_auth.SmartAuthPlugin.startSmsRetriever(SmartAuthPlugin.kt:241)
E/MethodChannel#fman.smart_auth( 5268): 	at fman.ge.smart_auth.SmartAuthPlugin.onMethodCall(SmartAuthPlugin.kt:72)
E/MethodChannel#fman.smart_auth( 5268): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#fman.smart_auth( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#fman.smart_auth( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#fman.smart_auth( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#fman.smart_auth( 5268): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#fman.smart_auth( 5268): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#fman.smart_auth( 5268): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#fman.smart_auth( 5268): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/MethodChannel#fman.smart_auth( 5268): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#fman.smart_auth( 5268): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
E/MethodChannel#fman.smart_auth( 5268): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
E/MethodChannel#fman.smart_auth( 5268): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
E/MethodChannel#fman.smart_auth( 5268): 	at android.os.Binder.execTransact(Binder.java:1275)
E/MethodChannel#fman.smart_auth( 5268):

Pinput/SmartAuth: getSmsCode failed: PlatformException(error, com.caddcentre.lms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.caddcentre.lms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
I/flutter ( 5268): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
I/flutter ( 5268): 	at android.os.Parcel.createException(Parcel.java:3041)
I/flutter ( 5268): 	at android.os.Parcel.readException(Parcel.java:3024)
I/flutter ( 5268): 	at android.os.Parcel.readException(Parcel.java:2966)
I/flutter ( 5268): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
I/flutter ( 5268): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
I/flutter ( 5268): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
I/flutter ( 5268): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
I/flutter ( 5268): 	at fman.ge.smart_auth.SmartAuthPlugin.startSmsRetriever(SmartAuthPlugin.kt:241)
I/flutter ( 5268): 	at fman.ge.smart_auth.SmartAuthPlugin.onMethodCall(SmartAuthPlugin.kt:72)
I/flutter ( 5268): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter ( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter ( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter ( 5268): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 5268): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter ( 5268): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 5268): 	at android.os.Looper.loopOnce(Looper.java:205)
I/flutter ( 5268): 	at android.os.Looper.loop(Looper.java:294)
I/flutter ( 5268): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
I/flutter ( 5268): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 5268): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
I/flutter ( 5268): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter ( 5268): Caused by: android.os.RemoteException: Remote stack trace:
I/flutter ( 5268): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
I/flutter ( 5268): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
I/flutter ( 5268): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
I/flutter ( 5268): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
I/flutter ( 5268): 	at android.os.Binder.execTransact(Binder.java:1275)
I/flutter ( 5268):
I/flutter ( 5268): )

**Comment by tolotrasamuel** [comment]
Should be fixed with 2.2.0. Please comment if still not working
