### ISSUE TITLE
Error when MainActivity extends FlutterFragmentActivity.

### ISSUE THREAD

**Issue by fjaroli** [tolotrasamuel/account_picker#2]
java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
	at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
	at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:687)
	at com.tolotra.account_picker.AccountPicker.requestPhoneHint(AccountPicker.java:66)
	at com.tolotra.account_picker.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:32)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:182)
	at android.app.ActivityThread.main(ActivityThread.java:7826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
	

**There is solution for this problem. Please check and update repository.** [https://stackoverflow.com/a/33332468](url)

**Comment by tolotrasamuel** [comment]
Please check 2.2.0, this should be fix. Let me know if the issue still persist
